import { useState } from "react";
import "./Output.css";
import useTerminal from "../../hooks/useTerminal";
import { FaCheckCircle, FaTimesCircle, FaClock, FaCode, FaCopy, FaTrash, FaPlay } from "react-icons/fa";

function Output() {
  const { latestExecution, runActiveFile, isRunning } = useTerminal();
  const [copied, setCopied] = useState(false);

  if (!latestExecution) {
    return (
      <div className="output-empty-state">
        <FaCode className="empty-icon" />
        <p>No execution output available yet.</p>
        <span>Execute code in the Hyperion Terminal or click the ▶ Run button to view execution results here.</span>
        <button
          className="output-run-now-btn"
          onClick={() => runActiveFile()}
          disabled={isRunning}
        >
          <FaPlay /> Run Active File Now
        </button>
      </div>
    );
  }

  const { filename, language, timestamp, duration, exitCode, success, stdout, stderr } = latestExecution;

  const handleCopy = () => {
    const text = [
      `=== Hyperion Execution: ${filename} (${language}) ===`,
      `Time: ${timestamp} | Duration: ${duration}ms | Exit Code: ${exitCode}`,
      stdout ? `\n--- STDOUT ---\n${stdout}` : '',
      stderr ? `\n--- STDERR ---\n${stderr}` : ''
    ].filter(Boolean).join('\n');

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="output-panel-container">
      <div className="output-meta-header">
        <div className="output-meta-left">
          <span className={`output-badge ${success ? 'badge-success' : 'badge-error'}`}>
            {success ? <FaCheckCircle /> : <FaTimesCircle />}
            {success ? 'SUCCESS' : 'FAILED'} (Exit {exitCode ?? 0})
          </span>
          <span className="output-meta-item">
            <strong>Target:</strong> {filename}
          </span>
          <span className="output-meta-item lang-tag">
            {language?.toUpperCase()}
          </span>
          <span className="output-meta-item">
            <FaClock /> {duration}ms
          </span>
          <span className="output-timestamp">{timestamp}</span>
        </div>

        <div className="output-meta-right">
          <button className="output-action-btn" onClick={handleCopy} title="Copy Execution Logs">
            <FaCopy /> {copied ? 'Copied!' : 'Copy'}
          </button>
          <button
            className="output-action-btn run-btn-output"
            onClick={() => runActiveFile()}
            disabled={isRunning}
            title="Re-run code"
          >
            <FaPlay /> Run Again
          </button>
        </div>
      </div>

      <div className="output-body">
        {stdout && (
          <div className="output-block stdout-block">
            <div className="output-block-title">STANDARD OUTPUT:</div>
            <pre className="output-text">{stdout}</pre>
          </div>
        )}

        {stderr && (
          <div className="output-block stderr-block">
            <div className="output-block-title">STANDARD ERROR:</div>
            <pre className="output-text stderr-text">{stderr}</pre>
          </div>
        )}

        {!stdout && !stderr && (
          <div className="output-block">
            <pre className="output-text muted-text">(No console output generated by program)</pre>
          </div>
        )}
      </div>
    </div>
  );
}

export default Output;
